#!/bin/bash

logdir=/home/inaki/Documents/meter_logs/

find "$logdir" -type f -mtime +30 -name '*.txt' -execdir rm -- '{}' \;

if [ ! -z $2 ]
then
	fname=$(ls -tr $logdir | tail -1)
	nvim "$logdir$fname"
else
	now='dlms_client_'$(date '+%Y%m%d_%H%M%S')
	fname="$logdir$now.txt"
	echo $fname
	/home/inaki/dev/lib/libmcoms_git/tools/mcoms_tools_hdlc_dlms_client -p 0x11 -d /dev/serial/by-id/usb-FTDI_USB__-__Serial-if00-port0 -c 2 -o 1024 < $1 2>&1 | ts [%m/%d-%H:%M:%.S] | tee -a "$fname"
fi
