#!/bin/bash

logdir=/home/inaki/Documents/zivos_logs/

find "$logdir" -type f -mtime +30 -name '*.txt' -execdir rm -- '{}' \;

#if [ ! -z $2 ]
if [ $1 == "l" ]
then
	fname=$(ls -tr $logdir | tail -1)
	nvim "$logdir$fname"
else
	now=$(date '+%Y%m%d_%H%M%S')
	fname="$logdir$now.txt"
	echo $fname
	#make qemu 2>&1 | tee "$fname"
	$1 2>&1 | tee "$fname"

fi
