#!/bin/bash

logdir=/home/inaki/Documents/meter_logs/

find "$logdir" -type f -mtime +30 -name '*.txt' -execdir rm -- '{}' \;

if [ ! -z $1 ]
then
	fname=$(ls -tr $logdir | tail -1)
	nvim "$logdir$fname"
	#vim "$fname"
else
	now=$(date '+%Y%m%d_%H%M%S')
	fname="$logdir$now.txt"
	echo $fname
	make emul | ts [%m/%d-%H:%M:%.S] | tee "$fname"
fi
