#!/bin/bash

logdir=/home/inaki/Documents/meter_logs/

find "$logdir" -type f -mtime +30 -name '*.txt' -execdir rm -- '{}' \;

if [ ! -z $1 ]
then
	fname=$(ls -tr $logdir | tail -1)
	nvim "$logdir$fname"
	#vim "$fname"
else
	if [ -L /dev/serial/by-id/usb-FTDI_TTL232R-3V3_FT59OJ7O-if00-port0 ]
	then
		dev=/dev/serial/by-id/usb-FTDI_TTL232R-3V3_FT59OJ7O-if00-port0
	elif [ -L /dev/serial/by-id/usb-FTDI_TTL232R-3V3_FTHBUEYX-if00-port0 ]
	then
		dev=/dev/serial/by-id/usb-FTDI_TTL232R-3V3_FTHBUEYX-if00-port0
	elif [ -L /dev/serial/by-id/usb-FTDI_TTL232R-3V3_FTHEUT88-if00-port0 ]
	then
		dev=/dev/serial/by-id/usb-FTDI_TTL232R-3V3_FTHEUT88-if00-port0
	fi

	now=$(date '+%Y%m%d_%H%M%S')
	fname="$logdir$now.txt"
	echo $fname
	#picocom -b 921600 /dev/serial/by-id/usb-FTDI_TTL232R-3V3_FT59OJ7O-if00-port0 | ts [%m/%d-%H:%M:%.S] | tee "$fname"
	picocom -b 921600 $dev | ts [%m/%d-%H:%M:%.S] | tee "$fname"
fi



