--require'shade'.setup({
--  overlay_opacity = 10,
--  opacity_step = 1,
--  keys = {
--    brightness_up    = '<C-m>',
--    brightness_down  = '<C-n>',
--    toggle           = '<Leader>m',
--  }
--})
